### ISSUE TITLE
Collection pages fail to load in boilerplate instance with test data

### ISSUE THREAD

**Issue by gwiedeman** [projectblacklight/arclight#1022]
A default install of Arclight 0.4.0 fails to show collection pages when using both our data and the example data using Rails 5.2.4.4 and Ruby 2.6.5. The page fails to load and rails server freezes and has to be killed manually. I only have easy access to windows at the moment, but this was the case for both WSL 1 and 2 so I don't *think* its an environment issue. The same result happened for the example EAD and a multiple of our EADs, so I don't suspect its an indexing or data issue.

### To reproduce
1. Use fresh rvm gemset
2. `gem install rails -v 5.2.4.4`
3. `rails new rails new my-app -m https://raw.githubusercontent.com/projectblacklight/arclight/master/template.rb` ([https://github.com/projectblacklight/arclight/wiki/Creating,-installing,-and-running-your-ArcLight-application](https://github.com/projectblacklight/arclight/wiki/Creating,-installing,-and-running-your-ArcLight-application))
4. `cd my-app`
5. `bundle install`
6. `gem install solr_wrapper`
7. `solr_wrapper`
8. (New terminal with same gemset) `mkdir eads` ([https://github.com/projectblacklight/arclight/wiki/Indexing-EAD-in-ArcLight](https://github.com/projectblacklight/arclight/wiki/Indexing-EAD-in-ArcLight))
9. `wget -P eads/ https://raw.githubusercontent.com/sul-dlss/arclight/master/spec/fixtures/ead/nlm/alphaomegaalpha.xml`
10. `REPOSITORY_ID=nlm traject -u http://127.0.0.1:8983/solr/blacklight-core -i xml -c /home/greg/.rvm/gems/ruby-2.6.5@arctest/bundler/gems/arclight-b1f67c197fad/lib/arclight/traject/ead2_config.rb eads/alphaomegaalpha.xml`
11. `rails s`
12. Browse to [http://localhost:3000/catalog/aoa271](http://localhost:3000/catalog/aoa271)

### Gem List
```
*** LOCAL GEMS ***

actioncable (5.2.4.4)
actionmailer (5.2.4.4)
actionpack (5.2.4.4)
actionview (5.2.4.4)
activejob (5.2.4.4)
activemodel (5.2.4.4)
activerecord (5.2.4.4)
activestorage (5.2.4.4)
activesupport (5.2.4.4)
addressable (2.7.0)
archive-zip (0.12.0)
arel (9.0.0)
autoprefixer-rails (10.2.0.0)
bcrypt (3.1.16)
bigdecimal (default: 1.4.1)
bindex (0.8.1)
blacklight (7.15.0)
blacklight-locale_picker (0.3.0)
blacklight_range_limit (7.9.1)
bootsnap (1.6.0)
bootstrap (4.6.0)
builder (3.2.4)
bundler (default: 1.17.3)
bundler-unload (1.0.2)
byebug (11.1.3)
capybara (3.35.1)
childprocess (3.0.0)
chromedriver-helper (2.1.1)
cmath (default: 1.0.0)
coffee-rails (4.2.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.1.8)
crass (1.0.6)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
deprecation (1.1.0)
devise (4.7.3)
devise-guests (0.7.0)
did_you_mean (1.3.0)
domain_name (0.5.20190701)
dot-properties (0.1.3)
e2mmap (default: 0.1.0)
erubi (1.10.0)
etc (default: 1.0.1)
execjs (2.7.0)
executable-hooks (1.6.0)
faraday (1.3.0)
faraday-net_http (1.0.1)
fcntl (default: 1.0.0)
ffi (1.14.2)
ffi-compiler (1.0.1)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
gem-wrappers (1.4.0)
globalid (0.4.2)
hashie (4.1.0)
http (4.4.1)
http-cookie (1.0.3)
http-form_data (2.3.0)
http-parser (1.2.3)
httpclient (2.8.3)
i18n (1.8.7)
io-console (default: 0.4.7)
io-like (0.3.1)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
jbuilder (2.11.2)
jquery-rails (4.4.0)
json (default: 2.1.0)
jsonpath (1.1.0)
kaminari (1.2.1)
kaminari-actionview (1.2.1)
kaminari-activerecord (1.2.1)
kaminari-core (1.2.1)
listen (3.1.5)
logger (default: 1.3.0)
loofah (2.9.0)
mail (2.7.1)
marc (1.0.4)
marc-fastxmlwriter (1.0.0)
marcel (0.3.3)
matrix (default: 0.1.0)
method_source (1.0.0)
mimemagic (0.3.5)
mini_mime (1.0.2)
mini_portile2 (2.5.0)
minitest (5.14.3, 5.11.3)
msgpack (1.4.1)
multi_json (1.15.0)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
nio4r (2.5.4)
nokogiri (1.11.1 x86_64-linux)
openssl (default: 2.1.2)
orm_adapter (0.5.0)
ostruct (0.3.3, default: 0.1.0)
popper_js (1.16.0)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.6)
puma (3.12.6)
racc (1.5.2)
rack (2.2.3)
rack-test (1.1.0)
rails (5.2.4.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.3.0)
railties (5.2.4.4)
rake (13.0.3, 12.3.2)
rb-fsevent (0.10.4)
rb-inotify (0.10.1)
rdoc (default: 6.1.2)
regexp_parser (2.0.3)
responders (3.0.1)
retriable (3.1.2)
rexml (default: 3.1.9)
rsolr (2.3.0)
rss (default: 0.2.7)
ruby-progressbar (1.11.0)
ruby2_keywords (0.0.4)
ruby_dep (1.5.0)
rubygems-bundler (1.4.5)
rubyzip (2.3.0)
rvm (1.11.3.9)
sass (3.7.4)
sass-listen (4.0.0)
sass-rails (5.1.0)
sassc (2.4.0)
sassc-rails (2.1.2)
scanf (default: 1.0.0)
schmooze (0.1.6)
scrub_rb (1.0.1)
sdbm (default: 1.0.0)
selenium-webdriver (3.142.7)
shell (default: 0.7)
slop (4.8.2)
solr_wrapper (3.0.1)
spring (2.1.1)
spring-watcher-listen (2.0.1)
sprockets (3.7.2)
sprockets-bumble_d (2.2.0)
sprockets-rails (3.2.2)
sqlite3 (1.4.2)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.2.9)
thor (1.1.0)
thread_safe (0.3.6)
thwait (default: 0.1.0)
tilt (2.0.10)
tracer (default: 0.1.0)
traject (3.5.0)
traject_plus (1.3.0)
turbolinks (5.2.1)
turbolinks-source (5.2.0)
twitter-typeahead-rails (0.11.1.pre.corejavascript)
tzinfo (1.2.9)
uglifier (4.2.0)
unf (0.1.4)
unf_ext (0.0.7.7)
view_component (2.25.0)
warden (1.2.9)
web-console (3.7.0)
webrick (default: 1.4.2)
websocket-driver (0.7.3)
websocket-extensions (0.1.5)
xmlrpc (0.3.0)
xpath (3.2.0)
yell (2.2.2)
zlib (default: 1.0.0)
```
### Stack trace

```
.... [first line repeated indefinitely]...
activesupport (5.2.4.4) lib/active_support/core_ext/object/try.rb:8:in `try'
activesupport (5.2.4.4) lib/active_support/core_ext/object/try.rb:8:in `try'
activesupport (5.2.4.4) lib/active_support/core_ext/object/try.rb:8:in `try'
activesupport (5.2.4.4) lib/active_support/core_ext/object/try.rb:8:in `try'
/mnt/c/Users/gw234478/ubuntu/arclight/app/controllers/concerns/arclight/field_config_helpers.rb:91:in `link_to_name_facet'
actionpack (5.2.4.4) lib/abstract_controller/helpers.rb:67:in `link_to_name_facet'
blacklight (7.15.0) app/presenters/blacklight/rendering/helper_method.rb:17:in `render_helper'
blacklight (7.15.0) app/presenters/blacklight/rendering/helper_method.rb:8:in `render'
blacklight (7.15.0) app/presenters/blacklight/rendering/pipeline.rb:43:in `render'
blacklight (7.15.0) app/presenters/blacklight/field_presenter.rb:37:in `render'
blacklight (7.15.0) app/presenters/blacklight/document_presenter.rb:97:in `field_value'
/mnt/c/Users/gw234478/ubuntu/arclight/app/views/catalog/_custom_metadata.html.erb:12:in `block (2 levels) in __mnt_c__sers_gw_______ubuntu_arclight_app_views_catalog__custom_metadata_html_erb__1000659798350672026_70183208461580'
/mnt/c/Users/gw234478/ubuntu/arclight/app/views/catalog/_custom_metadata.html.erb:9:in `each'
/mnt/c/Users/gw234478/ubuntu/arclight/app/views/catalog/_custom_metadata.html.erb:9:in `block in __mnt_c__sers_gw_______ubuntu_arclight_app_views_catalog__custom_metadata_html_erb__1000659798350672026_70183208461580'
actionview (5.2.4.4) lib/action_view/helpers/capture_helper.rb:41:in `block in capture'
actionview (5.2.4.4) lib/action_view/helpers/capture_helper.rb:205:in `with_output_buffer'
actionview (5.2.4.4) lib/action_view/helpers/capture_helper.rb:41:in `capture'
actionview (5.2.4.4) lib/action_view/helpers/tag_helper.rb:272:in `content_tag'
/mnt/c/Users/gw234478/ubuntu/arclight/app/views/catalog/_custom_metadata.html.erb:3:in `__mnt_c__sers_gw_______ubuntu_arclight_app_views_catalog__custom_metadata_html_erb__1000659798350672026_70183208461580'
actionview (5.2.4.4) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.4.4) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.4.4) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.4.4) lib/action_view/template.rb:157:in `render'
actionview (5.2.4.4) lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
actionview (5.2.4.4) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.4.4) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.4.4) lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
actionview (5.2.4.4) lib/action_view/renderer/partial_renderer.rb:312:in `render'
actionview (5.2.4.4) lib/action_view/renderer/renderer.rb:49:in `render_partial'
actionview (5.2.4.4) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.2.4.4) lib/action_view/helpers/rendering_helper.rb:33:in `render'
view_component (2.25.0) lib/view_component/render_monkey_patch.rb:9:in `render'
/mnt/c/Users/gw234478/ubuntu/arclight/app/views/catalog/_collection_context.html.erb:11:in `block in __mnt_c__sers_gw_______ubuntu_arclight_app_views_catalog__collection_context_html_erb__4405770881716821041_70183197335640'
/mnt/c/Users/gw234478/ubuntu/arclight/app/views/catalog/_collection_context.html.erb:9:in `each'
/mnt/c/Users/gw234478/ubuntu/arclight/app/views/catalog/_collection_context.html.erb:9:in `__mnt_c__sers_gw_______ubuntu_arclight_app_views_catalog__collection_context_html_erb__4405770881716821041_70183197335640'
actionview (5.2.4.4) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.4.4) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.4.4) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.4.4) lib/action_view/template.rb:157:in `render'
actionview (5.2.4.4) lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
actionview (5.2.4.4) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.4.4) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.4.4) lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
actionview (5.2.4.4) lib/action_view/renderer/partial_renderer.rb:312:in `render'
actionview (5.2.4.4) lib/action_view/renderer/renderer.rb:49:in `render_partial'
actionview (5.2.4.4) lib/action_view/helpers/rendering_helper.rb:36:in `render'
view_component (2.25.0) lib/view_component/render_monkey_patch.rb:9:in `render'
/mnt/c/Users/gw234478/ubuntu/arclight/app/views/catalog/_show_collection.html.erb:44:in `__mnt_c__sers_gw_______ubuntu_arclight_app_views_catalog__show_collection_html_erb__3552778860569330736_70183194180460'
actionview (5.2.4.4) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.4.4) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.4.4) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.4.4) lib/action_view/template.rb:157:in `render'
blacklight (7.15.0) app/helpers/blacklight/render_partials_helper_behavior.rb:67:in `render_document_partial'
blacklight (7.15.0) app/helpers/blacklight/render_partials_helper_behavior.rb:31:in `block in render_document_partials'
blacklight (7.15.0) app/helpers/blacklight/render_partials_helper_behavior.rb:30:in `map'
blacklight (7.15.0) app/helpers/blacklight/render_partials_helper_behavior.rb:30:in `render_document_partials'
blacklight (7.15.0) app/views/catalog/_show_main_content.html.erb:22:in `block (2 levels) in __home_greg__rvm_gems_ruby_______gems_blacklight________app_views_catalog__show_main_content_html_erb___27877037459964516_70183091838360'
actionview (5.2.4.4) lib/action_view/helpers/capture_helper.rb:41:in `block in capture'
actionview (5.2.4.4) lib/action_view/helpers/capture_helper.rb:205:in `with_output_buffer'
actionview (5.2.4.4) lib/action_view/helpers/capture_helper.rb:41:in `capture'
view_component (2.25.0) lib/view_component/base.rb:150:in `with'
blacklight (7.15.0) app/views/catalog/_show_main_content.html.erb:20:in `block in __home_greg__rvm_gems_ruby_______gems_blacklight________app_views_catalog__show_main_content_html_erb___27877037459964516_70183091838360'
actionview (5.2.4.4) lib/action_view/helpers/capture_helper.rb:41:in `block in capture'
actionview (5.2.4.4) lib/action_view/helpers/capture_helper.rb:205:in `with_output_buffer'
actionview (5.2.4.4) lib/action_view/helpers/capture_helper.rb:41:in `capture'
view_component (2.25.0) lib/view_component/base.rb:74:in `render_in'
view_component (2.25.0) lib/view_component/render_monkey_patch.rb:7:in `render'
blacklight (7.15.0) app/views/catalog/_show_main_content.html.erb:6:in `__home_greg__rvm_gems_ruby_______gems_blacklight________app_views_catalog__show_main_content_html_erb___27877037459964516_70183091838360'
actionview (5.2.4.4) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.4.4) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.4.4) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.4.4) lib/action_view/template.rb:157:in `render'
actionview (5.2.4.4) lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
actionview (5.2.4.4) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.4.4) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.4.4) lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
actionview (5.2.4.4) lib/action_view/renderer/partial_renderer.rb:312:in `render'
actionview (5.2.4.4) lib/action_view/renderer/renderer.rb:49:in `render_partial'
actionview (5.2.4.4) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.2.4.4) lib/action_view/helpers/rendering_helper.rb:33:in `render'
view_component (2.25.0) lib/view_component/render_monkey_patch.rb:9:in `render'
blacklight (7.15.0) app/helpers/blacklight/catalog_helper_behavior.rb:179:in `render_document_main_content_partial'
blacklight (7.15.0) app/views/catalog/show.html.erb:8:in `__home_greg__rvm_gems_ruby_______gems_blacklight________app_views_catalog_show_html_erb__2739841498740797407_70183091544100'
actionview (5.2.4.4) lib/action_view/template.rb:159:in `block in render'
activesupport (5.2.4.4) lib/active_support/notifications.rb:170:in `instrument'
actionview (5.2.4.4) lib/action_view/template.rb:354:in `instrument_render_template'
actionview (5.2.4.4) lib/action_view/template.rb:157:in `render'
actionview (5.2.4.4) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.2.4.4) lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.2.4.4) lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
actionview (5.2.4.4) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.2.4.4) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.2.4.4) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.2.4.4) lib/action_view/renderer/template_renderer.rb:16:in `render'
actionview (5.2.4.4) lib/action_view/renderer/renderer.rb:44:in `render_template'
actionview (5.2.4.4) lib/action_view/renderer/renderer.rb:25:in `render'
actionview (5.2.4.4) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.2.4.4) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (5.2.4.4) lib/action_view/rendering.rb:84:in `render_to_body'
actionpack (5.2.4.4) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.2.4.4) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.2.4.4) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (5.2.4.4) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'activesupport (5.2.4.4) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/home/greg/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
activesupport (5.2.4.4) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.2.4.4) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:45:in `render'
view_component (2.25.0) lib/view_component/rendering_monkey_patch.rb:9:in `render'
actionpack (5.2.4.4) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (5.2.4.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (5.2.4.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (5.2.4.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.4.4) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.4.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.4.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.4.4) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.4.4) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.4.4) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.4.4) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.4.4) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:840:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (5.2.4.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.4.4) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
railties (5.2.4.4) lib/rails/engine.rb:524:in `call'
puma (3.12.6) lib/puma/configuration.rb:227:in `call'
puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
puma (3.12.6) lib/puma/server.rb:476:in `process_client'
puma (3.12.6) lib/puma/server.rb:334:in `block in run'
puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by jkeck** [comment]
@gwiedeman should be addressed in the latest code on the master branch.  If you need a release w/ this soon, please let me know.
