### ISSUE TITLE
uninitialized constant Gem::BundlerVersionFinder (NameError)

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/arclight#1061]
I encounted this running tests:

```
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/dependency.rb:280:in `matching_specs': uninitialized constant Gem::BundlerVersionFinder (NameError)

    Gem::BundlerVersionFinder.prioritize!(matches) if prioritizes_bundler?
       ^^^^^^^^^^^^^^^^^^^^^^
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/dependency.rb:280:in `matching_specs'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2550:in `block in traverse'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `each'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:2548:in `traverse'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1034:in `block in find_in_unresolved_tree'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `each'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/specification.rb:1033:in `find_in_unresolved_tree'
	from <internal:/Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:114:in `require'
	from /Users/jcoyne85/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb:237:in `ensure_listeners_ready`
```

**Comment by jcoyne** [comment]
This is fixed by running `bundle exec rake` rather than `rake`
