### ISSUE TITLE
gem "blacklight_range_limit" missing from rails new template

### ISSUE THREAD

**Issue by gkostin1966** [projectblacklight/arclight#1386]
# NameError: uninitialized constant BlacklightRangeLimit  (see Tail of error output .... below)

### rails_new.sh
```
docker-compose build dock
docker-compose up --detach dock
docker-compose exec -- dock rails new arclight-app -m https://raw.githubusercontent.com/projectblacklight/arclight/main/template.rb
docker-compose down

```
### Dockerfile
```
FROM ruby:3.2

ARG UNAME=dock
ARG UID=1000
ARG GID=1000

RUN curl https://deb.nodesource.com/setup_12.x | bash
RUN curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -yqq && \
    apt-get install -yqq --no-install-recommends vim nodejs yarn sqlite3
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -d /opt/dock -u $UID -g $GID -o -s /bin/bash $UNAME

USER $UNAME

WORKDIR /opt/dock
RUN gem install rails

CMD ["sleep", "infinity"]
```
### docker-compose.yml
```
version: '3.7'

services:
  dock:
    image: dock
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/opt/dock
    command:
      - sleep
      - infinity

```

## Tail of error output ....
```
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
         run  bundle install
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using i18n 1.12.0
Using minitest 5.17.0
Using tzinfo 2.0.5
Using activesupport 7.0.4
Using builder 3.2.4
Using erubi 1.12.0
Using racc 1.6.2
Using nokogiri 1.14.0 (aarch64-linux)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.19.1
Using rails-html-sanitizer 1.4.4
Using actionview 7.0.4
Using rack 2.2.5
Using rack-test 2.0.2
Using actionpack 7.0.4
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.5
Using actioncable 7.0.4
Using globalid 1.0.0
Using activejob 7.0.4
Using activemodel 7.0.4
Using activerecord 7.0.4
Using marcel 1.0.2
Using mini_mime 1.1.2
Using activestorage 7.0.4
Using date 3.3.3
Using timeout 0.3.1
Using net-protocol 0.2.1
Using net-imap 0.3.4
Using net-pop 0.1.2
Using net-smtp 0.3.3
Using mail 2.8.0.1
Using actionmailbox 7.0.4
Using actionmailer 7.0.4
Using actiontext 7.0.4
Using public_suffix 5.0.1
Using addressable 2.8.1
Using deprecation 1.1.0
Using hashdiff 1.0.1
Using jbuilder 2.11.5
Using kaminari-core 1.2.2
Using kaminari-actionview 1.2.2
Using kaminari-activerecord 1.2.2
Using kaminari 1.2.2
Using ostruct 0.5.5
Using bundler 2.4.1
Using method_source 1.0.0
Using thor 1.2.1
Using zeitwerk 2.6.6
Using railties 7.0.4
Using rails 7.0.4
Using view_component 2.82.0
Using blacklight 7.33.0
Using blacklight_range_limit 8.2.3
Using rexml 3.2.5
Using dot-properties 0.1.4
Using hashie 5.0.0
Using unf_ext 0.0.8.2
Using unf 0.1.4
Using domain_name 0.5.20190701
Using http-cookie 1.0.5
Using http-form_data 2.3.0
Using ffi 1.15.5
Using ffi-compiler 1.0.1
Using llhttp-ffi 0.4.0
Using http 5.1.1
Using httpclient 2.8.3
Using scrub_rb 1.0.1
Using marc 1.2.0
Using marc-fastxmlwriter 1.1.0
Using slop 4.9.3
Using yell 2.2.2
Using traject 3.8.1
Using multi_json 1.15.0
Using jsonpath 1.1.2
Using traject_plus 2.0.0
Using arclight 0.5.0
Using execjs 2.8.1
Using autoprefixer-rails 10.4.7.0
Using bcrypt 3.1.18
Using bindex 0.8.1
Using blacklight-locale_picker 1.0.0
Using msgpack 1.6.0
Using bootsnap 1.15.0
Using popper_js 1.16.1
Using sassc 2.4.0
Using sprockets 4.2.0
Using sprockets-rails 3.4.2
Using tilt 2.0.11
Using sassc-rails 2.1.2
Using bootstrap 4.6.2
Using matrix 0.4.2
Using regexp_parser 2.6.1
Using xpath 3.2.0
Using capybara 3.38.0
Using debug 1.7.1
Using orm_adapter 0.5.0
Using responders 3.0.1
Using warden 1.2.9
Using devise 4.8.1
Using devise-guests 0.8.1
Using faraday-net_http 3.0.2
Using ruby2_keywords 0.0.5
Using faraday 2.7.2
Using importmap-rails 1.1.5
Using jquery-rails 4.5.1
Using minitar 0.9
Using puma 5.6.5
Using retriable 3.1.2
Using rsolr 2.5.0
Using ruby-progressbar 1.11.0
Using rubyzip 2.3.2
Using websocket 1.2.9
Using selenium-webdriver 4.7.1
Using solr_wrapper 4.0.2
Using sqlite3 1.6.0 (aarch64-linux)
Using stimulus-rails 1.2.1
Using turbo-rails 1.3.2
Using twitter-typeahead-rails 0.11.1.pre.corejavascript
Using web-console 4.2.0
Using webdrivers 5.2.0
Bundle complete! 25 Gemfile dependencies, 125 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
rails aborted!
NameError: uninitialized constant BlacklightRangeLimit
/opt/dock/arclight-app/config/routes.rb:2:in `block in <main>'
/opt/dock/arclight-app/config/routes.rb:1:in `<main>'
/opt/dock/arclight-app/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
rails aborted!
NameError: uninitialized constant BlacklightRangeLimit
/opt/dock/arclight-app/config/routes.rb:2:in `block in <main>'
/opt/dock/arclight-app/config/routes.rb:1:in `<main>'
/opt/dock/arclight-app/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
Run turbo:install:redis to switch on Redis and use it in development for turbo streams
rails aborted!
NameError: uninitialized constant BlacklightRangeLimit
/opt/dock/arclight-app/config/routes.rb:2:in `block in <main>'
/opt/dock/arclight-app/config/routes.rb:1:in `<main>'
/opt/dock/arclight-app/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
[+] Running 2/1
 ⠿ Container blacklight_range_limit-dock-1  Removed                       10.4s
 ⠿ Network blacklight_range_limit_default   Removed                        0.0s
```

**Comment by jcoyne** [comment]
BlacklightRangeLimit was removed on purpose because there is nothing in Arclight that requires you to use it and it's not updated to work with Blacklight 8 or Bootstrap 5.

**Comment by barmintor** [comment]
I was about to PR a change to add this dependency back in before seeing this issue. My problem was that I was running the rails app generation from ruby 2.7 - this pulls the latest version of arclight that supports that ruby version in (v0.5.0), and the old install generator inserts route helpers from BlacklightRangeLimit that interfere with the app generation. Running from ruby 3 and speccing arclight to `~> 1.0` in the template cleared the issue up.
