### ISSUE TITLE
Indexer issues with large finding aids / indexer dying without much detail

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#472]
In prepping for the July demo with Stanford SPEC, I noticed that a larger than usual finding aid (Buckminster Fuller papers, ~8 MB EAD, 25+ series with 17,000+ components total) was not indexing completely.

The error below suggested that only individual documents were not being processed by Solr because of a 502 error, but it looks like only two of the series actually got indexed.

In addition, it appears that neither the EC2 instance used for the demo app or the Solr server were running out of memory.

Specifically, this was getting written to the console for `ec2-user`:

```
rake aborted!
RSolr::Error::Http: RSolr::Error::Http - 502 Bad Gateway
Error: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>
URI: http://blacklight-solr-internal-prod.us-west-2.elasticbeanstalk.com/solr/arclight_demo/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">m1090-xmlaspace_ref8612_ij3</field><field name=\"ead_ssi\">m1090.xml</field><field name=\"parent_ssi\">aspace_ref201_h8u</field><field name=\"parent_ssm\">m1090-xml</field><field name=\"parent_ssm\">aspace_ref200_kca</field><field name=\"parent_ssm\">aspace_ref201_h8u</field><field name=\"parent_unittitles_ssm\">R. Buckminster Fuller papers, circa 1920-1983</field><field name=\"parent_unittitles_ssm\">Series 2. Dymaxion Chronofile</field><field name=\"parent_unittitles_ssm\">Subseries 1. Volumes</field><field name=\"parent_unittitles_teim\">R. Buckminster Fuller papers, circa 1920-1983</field><field name=\"parent_unittitles_teim\">Series 2. Dymaxion Chronofile</field><field name=\"parent_unittitles_teim\">Subseries 1. Volumes</field><field name=\"component_level_isim\">3</field><field name=\"component_children_bsi\">false</field><field name=\"collection_sim\">R. Buckminster Fuller papers, circa 1920-1983</field><field name=\"collection_ssm\">R. Buckminster Fuller papers, circa 1920-1983</field><field name=\"repository_sim\">Stanford University Libraries. Special Collections and University Archives</field><field name=\"repository_ssm\">Stanford University Libraries. Special Collections and University Archives</field><field name=\"child_component_count_isim\">0</field><field name=\"parent_teim\">m1090-xml</field><field name=\"parent_teim\">aspace_ref200_kca</field><field name=\"parent_teim\">aspace_ref201_h8u</field><field name=\"collection_creator_ssm\">Fuller, R. Buckminster (Richard Buckminster)</field><field name=\"parent_access_restrict_ssm\">Open for research; material must be requested at least 36 hours in advance of intended use. Scholars should note that some items may be closed for conservation treatment. The original Dymaxion Transport drawings and blueprints in series 16, subseries 6 (map folder 114) and subseries 23 (map folders 81-107) are CLOSED; researchers should page USE COPIES. A sampling of models from series 19 are accessible for patron use but the rest of the models are CLOSED for viewing until conservation treatment can be completed.\nApproximately 5,000 slides from Series 15 have been digitized and accessible via digital surrogates in the reading room.\nAudio-visual material is currently unavailable; individual requests will require four weeks to reformat for patron use. As per legal agreement, copies of audio-visual material are only available in the Special Collections reading room unless explicit written permission from the copyright holder is obtained.</field><field name=\"parent_access_terms_ssm\">Property rights reside with the repository. Literary rights reside with the creators of the documents or their heirs. To obtain permission to publish or reproduce, please contact the Public Services Librarian of the Dept. of Special Collections.</field><field name=\"ref_ssm\">aspace_ref8612_ij3</field><field name=\"level_ssm\">file</field><field name=\"title_ssm\">Dymaxion Chronofile, Vol. 666, [7 of 7]</field><field name=\"title_si\">Dymaxion Chronofile, Vol. 666, [7 of 7]</field><field name=\"unitdate_ssm\">1978 June/July</field><field name=\"material_sim\">Mixed Materials</field><field name=\"material_ssm\">Mixed Materials</field><field name=\"scopecontent_ssm\">Chronofile. 1978 July 16 - 1978 July 7.</field><field name=\"scopecontent_teim\">Chronofile. 1978 July 16 - 1978 July 7.</field><field name=\"unitdate_inclusive_ssm\">1978 June/July</field><field name=\"ref_ssi\">aspace_ref8612_ij3</field><field name=\"level_sim\">File</field><field name=\"containers_ssim\">box 369</field><field name=\"containers_ssim\">folder 3</field><field name=\"has_online_content_ssim\">false</field><field name=\"normalized_title_ssm\">Dymaxion Chronofile, Vol. 666, [7 of 7], 1978 June/July</field><field name=\"normalized_date_ssm\">1978 June/July</field><field name=\"sort_ii\">3125</field></doc></add>"

Backtrace: /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
(eval):2:in `post'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:84:in `update'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:104:in `add'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/solr_ead-0.7.5/lib/solr_ead/indexer.rb:109:in `block in add_components'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:190:in `block in each'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `upto'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `each'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/solr_ead-0.7.5/lib/solr_ead/indexer.rb:106:in `add_components'
(eval):2:in `post'
Tasks: TOP => arclight:index
(See full trace by running task with --trace)
```

**Comment by billdueber** [comment]
I've submitted a [pull request](https://github.com/awead/solr_ead/pull/20) to the solr_ead project that removes a bunch of performance issues that I bet will help address this. 

A stand-alone benchmarking program (i.e., it monkeypatches stock SolrEad with the same code
as is in this pull request) is at https://gist.github.com/billdueber/027b6f9c35623889bb2d42c091c6efa3 -- it does the comparison, throwing out everything that's under 1s for both implementations as uninteresting, and timing out at the 10mn mark.

**Comment by jrees67** [comment]
I recently experienced this with much smaller files where the indexing hangs/never completes or claims of completion are untrue (1.2MB file supposedly completed in 1881 secs but was actually unfinished). I also noticed that the average indexing time per KB expands geometrically as files get larger. This on a Mac installation using solr_wrapper

**Comment by anarchivist** [comment]
@jrees67 We recently released a version of `solr_ead` which introduces some performance improvements - let me know if you need any assistance testing them, or feel free to send them along if you'd like us to test!

**Comment by anarchivist** [comment]
Closing because it's assumed that this is resolved and will improve with an indexer rewrite.
