### ISSUE TITLE
ActionView::Template::Error: couldn't find file 'blacklight/core' with type 'application/javascript'

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#482]
Probably will be fixed by projectblacklight/blacklight_range_limit#82

```
       ActionView::Template::Error:
         couldn't find file 'blacklight/core' with type 'application/javascript'
         Checked in these paths:
           /private/tmp/arclight/.internal_test_app/app/assets/config
           /private/tmp/arclight/.internal_test_app/app/assets/images
           /private/tmp/arclight/.internal_test_app/app/assets/javascripts
           /private/tmp/arclight/.internal_test_app/app/assets/stylesheets
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jquery-rails-4.3.3/vendor/assets/javascripts
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/twitter-typeahead-rails-0.11.1.pre.corejavascript/vendor/assets/javascripts
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight_range_limit-9b1d1664167f/app/assets/javascripts
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight_range_limit-9b1d1664167f/app/assets/stylesheets
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight_range_limit-9b1d1664167f/vendor/assets/javascripts
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight_range_limit-9b1d1664167f/vendor/assets/stylesheets
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/tether-rails-1.4.0/vendor/assets/javascripts
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/tether-rails-1.4.0/vendor/assets/stylesheets
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/coffee-rails-4.2.2/lib/assets/javascripts
           /private/tmp/arclight/app/assets/images
           /private/tmp/arclight/app/assets/javascripts
           /private/tmp/arclight/app/assets/stylesheets
           /private/tmp/arclight/vendor/assets/javascripts
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight-8b9041544553/app/assets/images
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight-8b9041544553/app/assets/javascripts
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight-8b9041544553/app/assets/stylesheets
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actioncable-5.1.6/lib/assets/compiled
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionview-5.1.6/lib/assets/compiled
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/turbolinks-source-5.1.0/lib/assets/javascripts
           /private/tmp/arclight/.internal_test_app/node_modules
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/popper_js-1.12.9/assets/javascripts
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-4.1.1/assets/stylesheets
           /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-4.1.1/assets/javascripts
       # ./spec/features/search_results_spec.rb:170:in `block (3 levels) in <top (required)>'
       # ------------------
       # --- Caused by: ---
       # Sprockets::FileNotFound:
       #   couldn't find file 'blacklight/core' with type 'application/javascript'
       #   Checked in these paths:
       #     /private/tmp/arclight/.internal_test_app/app/assets/config
       #     /private/tmp/arclight/.internal_test_app/app/assets/images
       #     /private/tmp/arclight/.internal_test_app/app/assets/javascripts
       #     /private/tmp/arclight/.internal_test_app/app/assets/stylesheets
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/jquery-rails-4.3.3/vendor/assets/javascripts
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/twitter-typeahead-rails-0.11.1.pre.corejavascript/vendor/assets/javascripts
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight_range_limit-9b1d1664167f/app/assets/javascripts
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight_range_limit-9b1d1664167f/app/assets/stylesheets
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight_range_limit-9b1d1664167f/vendor/assets/javascripts
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight_range_limit-9b1d1664167f/vendor/assets/stylesheets
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/tether-rails-1.4.0/vendor/assets/javascripts
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/tether-rails-1.4.0/vendor/assets/stylesheets
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/coffee-rails-4.2.2/lib/assets/javascripts
       #     /private/tmp/arclight/app/assets/images
       #     /private/tmp/arclight/app/assets/javascripts
       #     /private/tmp/arclight/app/assets/stylesheets
       #     /private/tmp/arclight/vendor/assets/javascripts
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight-8b9041544553/app/assets/images
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight-8b9041544553/app/assets/javascripts
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/blacklight-8b9041544553/app/assets/stylesheets
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actioncable-5.1.6/lib/assets/compiled
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionview-5.1.6/lib/assets/compiled
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/turbolinks-source-5.1.0/lib/assets/javascripts
       #     /private/tmp/arclight/.internal_test_app/node_modules
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/popper_js-1.12.9/assets/javascripts
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-4.1.1/assets/stylesheets
       #     /Users/matienzo/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-4.1.1/assets/javascripts
       #   ./spec/features/search_results_spec.rb:170:in `block (3 levels) in <top (required)>'```

**Comment by christinach** [comment]
This is not triggered any more because of the https://github.com/projectblacklight/blacklight_range_limit/commit/d26b56c8a51d93270249b2ca9beb26833339f91b update in `blacklight_range_limit (= 7.0.0.rc2)`

**Comment by mejackreed** [comment]
Thanks @christinach
