### ISSUE TITLE
Analysis and modification of fields for online content in traject indexing

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#600]
Field: `has_online_content_ssim` and `digital_objects_ssm`

Spun out of #567. Currently implemented but failing specs:
```
  43) Online Content Viewer embedded content renders digital object viewer initialization markup
      Failure/Error:
        expect(page).to have_css(
          '.al-oembed-viewer[data-arclight-oembed-url="http://purl.stanford.edu/kc844kt2526"]',
          visible: false
        )

        expected to find css ".al-oembed-viewer[data-arclight-oembed-url=\"http://purl.stanford.edu/kc844kt2526\"]" but there were no matches
      # ./spec/features/online_content_spec.rb:15:in `block (4 levels) in <top (required)>'
  44) Online Content Viewer non-embeddable content renders a list of links
      Failure/Error: click_link('Online content')

      Capybara::ElementNotFound:
        Unable to find link "Online content"
      # ./spec/features/online_content_spec.rb:31:in `block (4 levels) in <top (required)>'

  48) Search results search results renders the online content label when there is online content
      Failure/Error: expect(page).to have_css('.badge.badge-success', text: 'online content')
        expected to find css ".badge.badge-success" within #<Capybara::Node::Element tag="article" path="/html/body/div[3]/div[6]/section[1]/div[2]/article[1]"> but there were no matches
      # ./spec/features/search_results_spec.rb:48:in `block (4 levels) in <top (required)>'
      # ./spec/features/search_results_spec.rb:47:in `block (3 levels) in <top (required)>'
```
## Acceptance criteria
Using work in https://github.com/projectblacklight/arclight/issues/557#issuecomment-521801873, [`solr_document.rb`](https://github.com/projectblacklight/arclight/blob/master/app/models/concerns/arclight/solr_document.rb), and currently indexed fields 

 - [ ] determine if `has_online_content_ssim` is being indexed correctly (and any other similar fields)
 - [ ] implement / fix in traject config

**Comment by estelendur** [comment]
I'm not quite sure how to check for passing specs given that a lot of them currently fail for other reasons, but I did put together a fix that doesn't reiterate any of the failures given here.
